# Generated by Django 4.2.7 on 2023-12-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={"unique": "The Name entered already exists."},
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        error_messages={
                            "unique": "The Email Id entered already exists."
                        },
                        max_length=254,
                        unique=True,
                    ),
                ),
                ("notes", models.TextField(default="", max_length=200)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
